### ISSUE TITLE
PouchDB is not opening sqlite db with encryption support.

### ISSUE THREAD

**Issue by virtualit786** [litehelpers/Cordova-sqlcipher-adapter#24] opened 2016-03-17 10:57 UTC
Hi,
Main document for the sqlcipher plugin indicates the pouchdb is working this adaptor is part of pouchdb and thanks to nolanlawson who made it work. Based on this, I am trying the following code and PouchDB is not opening db as encrypted and displayed the following on console. 

> OPEN database: _pouch_userDB.txt
> open full db path: /var/mobile/Containers/Data/Application/99BA28C6-03BB-4636-9224-9EF708B79C94/Documents/_pouch_userDB.db
> Open DB with NO encryption
> 

Here is the code !
```
      var db2 = new PouchDB('userDB.db', {adapter: 'websql', key: 'password'});
      db2.info().then(console.log.bind(console));
      db2.put({_id: '1', name: 'username'})
        .then(usr => {
          console.log(`${usr} saved`);
        }).
        catch(ex=> {
          console.log(`${ex} occurred`)
        });

```

Where as the following works fine in the same app

```
      var db = window.sqlitePlugin.openDatabase({name: "my.db", key: "your-password-here"});
      db.transaction(function (tx) {
        tx.executeSql('DROP TABLE IF EXISTS test_table');
        tx.executeSql('CREATE TABLE IF NOT EXISTS test_table (id integer primary key, data text, data_num integer)');

        tx.executeSql("INSERT INTO test_table (data, data_num) VALUES (?,?)", ["test", 100], function (tx, res) {
          console.log("insertId: " + res.insertId + " -- probably 1");
          console.log("rowsAffected: " + res.rowsAffected + " -- should be 1");

          tx.executeSql("select count(id) as cnt from test_table;", [], function (tx, res) {
            console.log("res.rows.length: " + res.rows.length + " -- should be 1");
            console.log("res.rows.item(0).cnt: " + res.rows.item(0).cnt + " -- should be 1");
          });

        }, function (e) {
          console.log("ERROR: " + e.message);
        });
      });
```

And here is the console output!

> OPEN database: my.db
> open full db path: /var/mobile/Containers/Data/Application/99BA28C6-03BB-4636-9224-9EF708B79C94/Documents/my.db
> Open DB with encryption

**It will be really helpful if someone please point out the mistake. What am I missing to pass to PouchDB constructor ?**

**Comment by brodybits** [comment] 2016-03-17 11:00
It is a bug that cannot be fixed here. AFAIK PouchDB does not expect or handle the `key` option. Please file a bug on PouchDB (and reference it here).

**Comment by virtualit786** [comment] 2016-03-17 11:06
@brodybits I am going to report the bug as you suggested. But since its mentioned to be working with Cordova-sqlcipher-adapter plugin on its main page, can you or @nolanlawson point out how you made it work so I could at least get pass the blocker !

Thanks!

**Comment by brodybits** [comment] 2016-03-17 11:15
We made it work *without* encryption.

If you are interested in fixing PouchDB yourself, you may want to take a look at pouchdb/pouchdb#3617 which solved a similar problem with specifying the iOS database location.

**Comment by nolanlawson** [comment] 2016-03-17 14:51
Yes, it should be as easy as passing the `key` option along.

**Comment by robobit** [comment] 2016-03-17 14:58
Well almost. PouchDB caches the database objects and doesn't take the options into account for this.
What happen because of this if you try to open the database with a wrong key (ie. user entered wrong password), you will not be able to try again with another key because the cached object will be used.

I fixed it like this:
```
 lib/pouchdb.js | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/lib/pouchdb.js b/lib/pouchdb.js
index 3ccb27f..ee6ad3c 100644
--- a/lib/pouchdb.js
+++ b/lib/pouchdb.js
@@ -5362,10 +5362,11 @@ function openDBSafely(openDBFunction, opts) {
 var cachedDatabases = {};
 
 function openDB(opts) {
-  var cachedResult = cachedDatabases[opts.name];
+  var key = JSON.stringify(opts);
+  var cachedResult = cachedDatabases[key];
   if (!cachedResult) {
     var openDBFun = createOpenDBFunction();
-    cachedResult = cachedDatabases[opts.name] = openDBSafely(openDBFun, opts);
+    cachedResult = cachedDatabases[key] = openDBSafely(openDBFun, opts);
     if (cachedResult.db) {
       cachedResult.db._sqlitePlugin = typeof sqlitePlugin !== 'undefined';
     }
```

**Comment by brodybits** [comment] 2016-03-25 11:30
> I have reported bug as you suggested and here is the link I have reported the bug on PouchDB issues [https://github.com/pouchdb/pouchdb/issues/4979](url).

The url link is broken. The issue is at: pouchdb/pouchdb#4979

**Comment by brodybits** [comment] 2016-04-19 22:06
This is now fixed in PouchDB.

**Closed by brodybits** 2016-04-19 22:06 UTC
Labels: bug, documentation, question
